name: tbwa-chat-orchestration
version: 3.2
tenant: tbwa-chat
description: "TBWA Chat interface orchestration pipeline with intelligent routing and reasoning traces"

variables:
  deepseek_model: "deepseek-coder:6.7b-instruct-q4_K_M"
  tinyllama_model: "tinyllama:latest"
  codellama_model: "codellama:7b-instruct"

stages:
  - name: intent-classification
    type: llm-router
    description: "Classify user intent to route to appropriate data sources"
    config:
      model: ${tinyllama_model}
      timeout: 5s
      patterns:
        campaign_analysis: 
          - "campaign|effectiveness|ROI|performance|advertising|marketing"
          - "budget|spend|cost|CPA|CTR|conversion"
          - "media|creative|targeting|audience"
        retail_insights:
          - "retail|store|product|scout|sales|revenue"
          - "inventory|stock|SKU|category|brand"
          - "customer|shopper|behavior|trends"
        cross_platform:
          - "compare|correlation|integration|holistic"
          - "campaign AND (retail|sales|store)"
        general_query:
          - ".*"
    outputs:
      - intent
      - confidence
      - reasoning

  - name: data-retrieval
    type: parallel
    description: "Retrieve data from appropriate sources based on intent"
    routes:
      - condition: "intent == 'campaign_analysis'"
        agent: ces-integration
        config:
          timeout: 15s
          include_trends: true
          metrics: ["impressions", "clicks", "conversions", "spend"]
          
      - condition: "intent == 'retail_insights'"
        agent: scout-integration
        config:
          timeout: 15s
          include_alerts: true
          data_sources: ["pos", "inventory", "customer"]
          
      - condition: "intent == 'cross_platform'"
        agent: multi-source-integration
        config:
          timeout: 30s
          sources: ["ces", "scout"]
          correlation_analysis: true
          
      - condition: "intent == 'general_query'"
        agent: knowledge-base
        config:
          timeout: 10s
          search_scope: "tbwa_knowledge"
    outputs:
      - data_results
      - sources
      - retrieval_time

  - name: reasoning-synthesis
    type: llm
    description: "Synthesize response with clear reasoning chain"
    config:
      model: ${deepseek_model}
      temperature: 0.3
      max_tokens: 2048
      prompt: |
        You are a TBWA campaign analytics assistant. Synthesize the following data with clear reasoning:
        
        Query: {query}
        Intent: {intent}
        Data: {data_results}
        Sources: {sources}
        
        Provide a comprehensive response that:
        1. Directly answers the user's question
        2. Highlights key insights from the data
        3. Explains your reasoning process
        4. Cites specific data sources
        5. Suggests actionable next steps if applicable
        
        Format your response in a conversational, professional tone suitable for TBWA clients.
        
        Response:
    outputs:
      - synthesized_response
      - confidence_score
      - key_insights

  - name: visualization-generation
    type: conditional
    description: "Generate visualization configuration if data supports it"
    condition: "data_results.length > 0 AND has_numeric_data(data_results)"
    config:
      visualization_types:
        campaign_analysis: "line-chart"
        retail_insights: "bar-chart"
        cross_platform: "combo-chart"
      theme:
        primary_color: "#00B5AD"  # TBWA Turquoise
        secondary_color: "#333333"  # TBWA Charcoal
        background: "#FFFFFF"
        grid_color: "#F5F5F5"
    outputs:
      - visualization_config
      - chart_data
      - layout_options

  - name: response-formatting
    type: final
    description: "Format final response with reasoning traces and sources"
    config:
      include_reasoning: true
      include_sources: true
      include_confidence: true
      format: "structured_json"
    outputs:
      - final_response

# Error handling configuration
error_handling:
  retry_attempts: 2
  timeout: 60s
  fallback_response: |
    I apologize, but I encountered an issue processing your request. 
    This might be due to temporary data unavailability or high system load. 
    Please try rephrasing your question or try again in a moment.

# Monitoring and logging
monitoring:
  log_level: "info"
  metrics:
    - processing_time
    - confidence_scores
    - error_rates
    - source_usage
  alerts:
    - condition: "error_rate > 5%"
      notification: "slack"
      channel: "#tbwa-chat-alerts"

# Security and compliance
security:
  tenant_isolation: true
  data_encryption: true
  audit_logging: true
  pii_detection: true
  access_controls:
    - role: "tbwa_user"
      permissions: ["read", "chat"]
    - role: "tbwa_admin"
      permissions: ["read", "chat", "admin"]

# Performance optimization
optimization:
  caching:
    enabled: true
    ttl: 300s  # 5 minutes
    keys: ["intent", "data_results"]
  
  parallel_execution:
    enabled: true
    max_concurrent: 3
  
  model_selection:
    strategy: "intelligent_routing"
    fallback_model: ${tinyllama_model}